apiVersion: v1
kind: Secret
metadata:
  name: grafana-serviceaccount-token
  namespace: ovms-prometheus
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
type: kubernetes.io/service-account-token
